### ISSUE TITLE
Add Invisible ReCaptcha to the page for file upload

### ISSUE THREAD

**Issue by Presto412** [Presto412/CryptoFS#6]
Add [Invisible Recaptcha](https://developers.google.com/recaptcha/docs/invisible) to the [index view](https://github.com/Presto412/CryptoFS/blob/master/src/views/index.ejs) for file upload, and to the validation in the backend as well. 

Recaptcha Secret and keys can be stored in the .env file

**Comment by chris--jones** [comment]
I'd like to tackle this

**Comment by Presto412** [comment]
Sure @chris--jones

**Comment by chris--jones** [comment]
This proved harder than I anticipated due to recaptcha requiring a callback, I have a working branch here: https://github.com/chris--jones/CryptoFS/tree/invisible-recaptcha, but I'm not happy with having to manually dispatch an input change event to trigger the form submit so I'm going to try and use the alternate api.

**Comment by chris--jones** [comment]
I figured it out, I had to expose a global via `window` object for recaptcha to play nice - made the code a lot simpler and less hacky.
