### ISSUE TITLE
Remove dependency on jQuery

### ISSUE THREAD

**Issue by Presto412** [Presto412/CryptoFS#8]
Most of the frontend code has heavily utilized jquery, and with modern JS DOM improvements, jquery is not exactly needed. You can refer [this website](http://youmightnotneedjquery.com/).

**Comment by dshubhadeep** [comment]
Can you assign this to me ?

**Comment by Presto412** [comment]
Sure

**Comment by chris--jones** [comment]
It sounds like this issue is more "remove jquery dependency" than clean up the code?

**Comment by Presto412** [comment]
Yes @chris--jones, it should be removing the dependency

**Comment by chris--jones** [comment]
There are still issues with the merged branch including a reference to $ and setting all elements to block when shown.

**Comment by dshubhadeep** [comment]
> There are still issues with the merged branch including a reference to $ and setting all elements to block when shown.
> 

There was an issue when we were setting display to an empty string, that's why I changed it back to block.

**Comment by chris--jones** [comment]
> 
> 
> > There are still issues with the merged branch including a reference to $ and setting all elements to block when shown.
> 
> There was an issue when we were setting display to an empty string, that's why I changed it back to block.

The only issue I could find was that the key management section was hidden via class rather than style attribute. Forcing display block on shown elements produces display problems like this:
![image](https://user-images.githubusercontent.com/10459377/96102850-b5e63600-0f22-11eb-9488-56b9fd61811b.png)

I'll submit a PR to fix these issues shortly.
